<?php require ('template/header.phtml'); ?>

<form action="<?php echo $_SERVER['PHP_SELF'] ?>" method="post">
    <label>Please enter your name and birthday:</label>
    <div>
        <br>
        <label>Your name: </label>
        <input type="text" name="name" value="<?php if (isset($_POST['name'])) {
            echo $_POST['name'];
        }
        ?>">
    </div>
    <div>
        <label>Your birthday (in DD/MM/YY format): </label>
        <input type="date" name="birthday" value="
        <?php if (isset($_POST['birthday'])) {
            echo $_POST['birthday'];
        }
        ?>">
    </div>
    <div>
        <input type="submit" name="submit" value="Submit">
        <input type="button" name="reset" value="Reset">
    </div>
</form>

<?php if (isset($view->result)) : ?>
    <p><?php echo $view->result ?></p>
<?php endif; ?>
<?php require('template/footer.phtml');
