<?php
require ('template/header.phtml'); ?>
<table>
    <tr>
        <th>Item</th>
        <th>Description</th>
        <th>Cost</th>
        <th>Purchase</th>
    </tr>
    <tr>
        <td>Sony TV</td>
        <td>32" LCD Widescreen</td>
        <td>£950</td>
        <td><a href="purchase.php?product=1">buy</a> </td>
    </tr>
    <tr>
        <td>Panasonic DVD</td>
        <td>DVD Player</td>
        <td>£80</td>
        <td><a href="purchase.php?product=2">buy</a></td>
    </tr>
    <tr>
        <td>Philips Video</td>
        <td>VHS Video Recorder</td>
        <td>£110</td>
        <td><a href="purchase.php?product=3">buy</td>
    </tr>
</table>

<?php require('template/footer.phtml') ?>